global:
  name: consul
  datacenter: useast
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    enableAgentMetrics: true

prometheus:
  enabled: true

server:
  replicas: 3

connectInject:
  enabled: true
  default: true

ui:
  enabled: true
  service:
    type: LoadBalancer

controller:
  enabled: true