---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: expense-to-db
spec:
  destination:
    name: expense-db-mssql
  sources:
    - name: expense
      action: allow
    - name: vault
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: expense-to-db-mysql
spec:
  destination:
    name: expense-db-mysql
  sources:
    - name: expense-v2
      action: allow
    - name: vault
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: vault
spec:
  destination:
    name: vault
  sources:
    - name: expense
      action: allow
    - name: expense-v2
      action: allow
    - name: expense-db-mysql
      action: allow
    - name: expense-db-mssql
      action: allow