---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: expense-db-mssql
spec:
  protocol: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: expense-db-mssql
  labels:
    app: expense-db-mssql
    framework: mssql
spec:
  selector:
    app: expense-db-mssql
    framework: mssql
  ports:
    - name: http
      protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense-db-mssql
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-db-mssql
  labels:
    app: expense-db-mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-db-mssql
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-framework: mssql
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9411"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: "expense-db-mssql"
        vault.hashicorp.com/agent-inject-secret-db: "expense/static/data/mssql"
        vault.hashicorp.com/agent-inject-template-db: |
          {{ with secret "expense/static/data/mssql" -}}
          export SA_PASSWORD="{{ .Data.data.db_login_password }}"
          {{- end }}
      labels:
        app: expense-db-mssql
        framework: mssql
    spec:
      serviceAccountName: expense-db-mssql
      containers:
        - name: expense-db-mssql
          image: "joatmon08/expense-db:mssql-2019"
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "y"
          command: ["/bin/bash"]
          args: ["-c", "source /vault/secrets/db && bash /usr/src/app/entrypoint.sh"]
          livenessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 60