version: "3.3"
services:

  consul:
    image: consul:1.10.3
    command: ["consul","agent","-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "./compose_configs/consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  expense-db-mysql:
    image: joatmon08/expense-db:mysql-8
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Testing!123
  expensedb_proxy_mysql:
    image: joatmon08/consul-envoy:v1.10.3-v1.18.4
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/expensedb-mysql.hcl
    volumes:
      - "./compose_configs/service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "expense-db-mysql"]
    network_mode: "service:expense-db-mysql"

  expense-db-mssql:
    image: joatmon08/expense-db:mssql-2019
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Testing!123
  expensedb_proxy_mssql:
    image: joatmon08/consul-envoy:v1.10.3-v1.18.4
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/expensedb-mssql.hcl
    volumes:
      - "./compose_configs/service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "expense-db-mssql"]
    network_mode: "service:expense-db-mssql"

  consul_template:
    image: hashicorp/consul-template:0.27.1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CT_LOCAL_CONFIG: |
        template {
          contents = <<EOH
        {{ range ls "toggles" }}
        {{ .Key }}={{ .Value }}{{ end }}
        EOH
          destination = "/tmp/toggles"
          wait {
            min = "2s"
            max = "5s"
          }
        }
    volumes:
      - "./report:/tmp"

  jaeger:
    image: jaegertracing/all-in-one:1.26
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - "./compose_configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.12

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16