version: "3.3"
services:
  report:
    image: joatmon08/report:dotnet
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    ports:
      - 5002:5002
    volumes:
      - "./report:/etc/report"
  report_proxy:
    image: joatmon08/consul-envoy:v1.11.4-v1.20.2
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/report-dotnet.hcl
    volumes:
      - "./compose_configs/service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "report-dotnet"]
    network_mode: "service:report"
  report_agent:
    image: consul:1.11.4
    restart: always
    command: ["consul","agent","-config-file=/config/agent.hcl","-config-dir=/config"]
    volumes:
      - "./compose_configs/consul_agent_config:/config"
    network_mode: "service:report"

networks:
  vpcbr:
    external:
      name: expense-report_vpcbr