global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'envoy'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.5.0.3:9102', '10.5.0.4:9102', '10.5.0.5:9102', '10.5.0.6:9102', '10.5.0.7:9102']
        labels:
          group: 'envoy'