global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "envoy"
    metrics_path: /metrics
    consul_sd_configs:
      - server: 10.5.0.2:8500
        tags:
          - expense-report
    relabel_configs:
      - source_labels: [__meta_consul_service_address]
        regex: "(.*)"
        replacement: "${1}:9102"
        target_label: "__address__"
        action: "replace"
