{
 "title": "Expense Report",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful Requests by Application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\",app=\"expense\"}[5m])) by (release) * 300",
     "legendFormat": "expense {{release}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\",app=\"report\"}[5m])) by (release) * 300",
     "legendFormat": "report {{release}}"
    }
   ]
  },
  {
   "title": "Errors by Application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\",app=\"expense\"}[5m])) by (release) * 300",
     "legendFormat": "expense {{release}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\",app=\"report\"}[5m])) by (release) * 300",
     "legendFormat": "report {{release}}"
    }
   ]
  },
  { "title": "Outlier Detection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active Outlier Ejections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active) by (consul_service,consul_service_subset)",
     "legendFormat": "{{consul_service}} {{consul_service_subset}}"
    }
   ]
  },
  {
   "title": "Detected Consecutive 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_detected_consecutive_5xx[5m])) by (consul_service, consul_service_subset) * 300",
     "legendFormat": "{{consul_service}} {{consul_service_subset}}"
    }
   ]
  },
  {
   "title": "Enforced Consecutive 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_enforced_consecutive_5xx[5m])) by (consul_service, consul_service_subset) * 300",
     "legendFormat": "{{consul_service}} {{consul_service_subset}}"
    }
   ]
  },
  { "title": "Databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Successful Database Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\",app=\"expense-db-mssql\"}[5m])) * 300",
     "legendFormat": "expense-db-mssql"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\",app=\"expense-db-mysql\"}[5m])) * 300",
     "legendFormat": "expense-db-mysql"
    }
   ]
  }
 ]
}