---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: expense-db-mysql
spec:
  protocol: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: expense-db-mysql
  labels:
    app: expense-db-mysql
    framework: mysql
spec:
  selector:
    app: expense-db-mysql
    framework: mysql
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense-db-mysql
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-db-mysql
  labels:
    app: expense-db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-db-mysql
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-framework: mysql
        consul.hashicorp.com/transparent-proxy: "false"
        # consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9411,8200"
        vault.hashicorp.com/log-level: "debug"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "expense-db-mysql"
        vault.hashicorp.com/agent-inject-secret-mysql: "expense/static/data/mysql"
        # vault.hashicorp.com/secret-volume-path-mysql: "/etc/mysql/conf.d"
        # vault.hashicorp.com/agent-inject-file-mysql: "config-file.cnf"
        vault.hashicorp.com/agent-inject-template-mysql: |
          [client]
          {{ with secret "expense/static/data/mysql" -}}
          user={{ .Data.db_login }}
          password={{ .Data.db_login_password }}
          {{- end }}
      labels:
        app: expense-db-mysql
        framework: mysql
    spec:
      serviceAccountName: expense-db-mysql
      containers:
        - name: expense-db-mysql
          image: "joatmon08/expense-db:mysql"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Testing!123"
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 60