---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-db-mssql
spec:
  provider: vault
  secretObjects:
    - secretName: vault-db-mssql
      type: Opaque
      data:
        - objectName: dbPassword
          key: password
  parameters:
    roleName: 'expense-db-mssql'
    vaultAddress: 'http://vault.default:8200'
    objects: |
      - objectName: "dbPassword"
        secretPath: "expense/static/data/mssql"
        secretKey: "db_login_password"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: expense-db-mssql
spec:
  protocol: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: expense-db-mssql
  labels:
    app: expense-db-mssql
    framework: mssql
spec:
  selector:
    app: expense-db-mssql
    framework: mssql
  ports:
    - name: http
      protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense-db-mssql
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-db-mssql
  labels:
    app: expense-db-mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-db-mssql
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-framework: mssql
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9411,8200"
      labels:
        app: expense-db-mssql
        framework: mssql
    spec:
      serviceAccountName: expense-db-mssql
      containers:
        - name: expense-db-mssql
          image: "joatmon08/expense-db:mssql-2019"
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-db-mssql
                  key: password
          volumeMounts:
            - name: 'vault-db-mssql'
              mountPath: '/mnt/secrets-store'
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 60
      volumes:
        - name: vault-db-mssql
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'vault-db-mssql'