---
apiVersion: v1
data:
  application.properties: |-
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    spring.zipkin.base-url=http://jaeger:9411/
    spring.zipkin.sender.type=web
    spring.datasource.url=jdbc:mysql://localhost:3306/DemoExpenses?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=expense
    spring.datasource.username=root
    spring.datasource.password=Testing!123
    server.port=5001
kind: ConfigMap
metadata:
  name: expense
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-v2
  labels:
    app: expense
    release: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense
      release: v2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "expense"
        consul.hashicorp.com/connect-service-upstreams: "expense-db-mysql:3306"
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9411"
        consul.hashicorp.com/service-meta-version: v2
      labels:
        app: expense
        release: v2
        framework: java
    spec:
      serviceAccountName: expense
      containers:
        - name: expense
          imagePullPolicy: Always
          image: "joatmon08/expense:java-v2"
          ports:
            - containerPort: 5001
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "/tmp/config/application.properties"
          volumeMounts:
            - name: application-config
              mountPath: "/tmp/config"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /api
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: application-config
          configMap:
            name: expense
            items:
              - key: application.properties
                path: application.properties
