---
apiVersion: v1
kind: Service
metadata:
  name: expense
  labels:
    app: expense
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: expense
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: expense
spec:
  protocol: http