---
apiVersion: v1
kind: Service
metadata:
  name: expense-v2
  labels:
    app: expense
    release: v2
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: expense
    release: v2
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense-v2
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: expense-v2
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-v2
  labels:
    app: expense
    release: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense
      release: v2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "expense-db-mysql:3306"
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9411"
        consul.hashicorp.com/service-meta-version: v2
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: "expense-v2"
        vault.hashicorp.com/agent-inject-secret-application.properties: "expense/database/mysql/creds/expense-v2"
        vault.hashicorp.com/secret-volume-path-application.properties: "/tmp/config"
        vault.hashicorp.com/agent-inject-template-application.properties: |
          spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
          spring.zipkin.base-url=http://jaeger:9411/
          spring.zipkin.sender.type=web
          spring.datasource.url=jdbc:mysql://localhost:3306/DemoExpenses?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=expense
          server.port=5001
          {{ with secret "expense/database/mysql/creds/expense-v2" -}}
          spring.datasource.username={{ .Data.username }}
          spring.datasource.password={{ .Data.password }}
          {{- end }}
      labels:
        app: expense
        release: v2
        framework: java
    spec:
      serviceAccountName: expense-v2
      containers:
        - name: expense
          image: "joatmon08/expense:java-v2"
          ports:
            - containerPort: 5001
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "/tmp/config/application.properties"
          livenessProbe:
            httpGet:
              path: /api
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
