---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: expense-to-db-mysql
spec:
  destination:
    name: expense-db-mysql
  sources:
    - name: expense
      action: allow
---
apiVersion: v1
data:
  application.properties: |-
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    spring.zipkin.base-url=http://${JAEGER_HOST:localhost}:9411/
    spring.zipkin.sender.type=web
    spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/DemoExpenses?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=expense
    spring.datasource.username=root
    spring.datasource.password=Testing!123
    server.port=${SERVER_PORT:8080}
kind: ConfigMap
metadata:
  name: expense
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense
  labels:
    app: expense
    release: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "expense-db-mysql:3306"
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9411"
        consul.hashicorp.com/service-meta-version: v2
      labels:
        app: expense
        release: v2
        framework: java
    spec:
      serviceAccountName: expense
      containers:
        - name: expense
          imagePullPolicy: Always
          image: "joatmon08/expense:java-v2"
          ports:
            - containerPort: 5001
          env:
            - name: JAEGER_HOST
              value: "jaeger"
            - name: SERVER_PORT
              value: "5001"
            - name: SPRING_CONFIG_LOCATION
              value: "/tmp/config/application.properties"
          volumeMounts:
            - name: application-config
              mountPath: "/tmp/config"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /api
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: application-config
          configMap:
            name: expense
            items:
              - key: application.properties
                path: application.properties
