---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: report-kong-proxy
spec:
  protocol: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: report
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - http:
        paths:
          - path: /api/report
            pathType: Prefix
            backend:
              service:
                name: report
                port:
                  number: 5002
