---
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: report
        - name: expense
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: report
spec:
  destination:
    name: report
  sources:
    - name: ingress-gateway
      permissions:
        - action: allow
          http:
            pathPrefix: /api/report/trip
            methods: ["GET"]
        - action: allow
          http:
            pathExact: /api/report/expense/version
            methods: ["GET"]
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: expense
spec:
  destination:
    name: expense
  sources:
    - name: report
      permissions:
        - action: allow
          http:
            pathPrefix: /api/expense/trip
            methods: ["GET"]
        - action: allow
          http:
            pathExact: /api
            methods: ["GET"]
    - name: ingress-gateway
      permissions:
        - action: allow
          http:
            pathPrefix: /api/expense
            methods: ["POST"]