---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: report
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/preserve-host: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api/report
            pathType: Prefix
            backend:
              service:
                name: report
                port:
                  number: 5002
          - path: /api/expense
            pathType: Exact
            backend:
              service:
                name: expense
                port:
                  number: 5001
