---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: report
spec:
  destination:
    name: report
  sources:
    - name: report-kong-proxy
      permissions:
        - action: allow
          http:
            pathExact: /api/report/expense/version
            methods: ['GET']
        - action: allow
          http:
            pathPrefix: /api/report/trip
            methods: ['GET']
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: expense
spec:
  destination:
    name: expense
  sources:
    - name: report
      permissions:
        - action: allow
          http:
            pathPrefix: /api/expense/trip
            methods: ['GET']
        - action: allow
          http:
            pathExact: /api
            methods: ['GET']
    - name: report-kong-proxy
      permissions:
        - action: allow
          http:
            pathExact: /api/expense
            methods: ['POST']
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: expense-to-db
spec:
  destination:
    name: expense-db-mssql
  sources:
    - name: expense
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: expense-to-db-mysql
spec:
  destination:
    name: expense-db-mysql
  sources:
    - name: expense
      action: allow
    - name: vault
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: vault
spec:
  destination:
    name: vault
  sources:
    - name: '*'
      action: allow