---
apiVersion: v1
kind: Service
metadata:
  name: report
  labels:
    app: report
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: report
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: report
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: report
spec:
  protocol: http
  upstreamConfig:
    overrides:
      - name: expense
        limits:
          maxConnections: 3
          maxPendingRequests: 4
          maxConcurrentRequests: 5
        passiveHealthCheck:
          interval: "30s"
          maxFailures: 10