---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  labels:
    app: report
    release: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
      release: v2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9411"
        consul.hashicorp.com/service-meta-version: v2
      labels:
        app: report
        release: v2
    spec:
      serviceAccountName: report
      containers:
        - name: report
          image: "joatmon08/report:dotnet-v2"
          ports:
            - containerPort: 5002
          livenessProbe:
            tcpSocket:
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 60
