---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: report
spec:
  defaultSubset: v2
  subsets:
    v2:
      filter: "Service.Meta.version == v2"
    v3:
      filter: "Service.Meta.version == v3"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: expense
spec:
  routes:
    - match:
        http:
          header:
            - name: x-debug
              exact: '1'
      destination:
        service: expense-v2

