ingressController:
  serviceAccount:
    name: report-kong-proxy

podAnnotations:
  consul.hashicorp.com/connect-inject: "true"
  consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9411"
  consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "8000,8443"