global:
  name: vault

server:
  annotations:
    consul.hashicorp.com/connect-inject: 'true'
    consul.hashicorp.com/connect-service: 'vault'
    consul.hashicorp.com/connect-service-port: '8200'
    consul.hashicorp.com/connect-service-upstreams: 'expense-db-mysql:3306,expense-db-mssql:1433'
    consul.hashicorp.com/transparent-proxy-exclude-outbound-cidrs: "199.36.153.4/30"
    consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "8200,8201"
    consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "8200,8201"
  ha:
    enabled: true
    raft:
      enabled: true
      config: |
        disable_mlock = true
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "http://vault:8200"
          }
        }

        service_registration "kubernetes" {}

        seal "gcpckms" {
          project     = "hc-93038b1ee86644cab765bc9a7b0"
          region      = "us-central1"
          key_ring    = "kubecon-a9yGfySh"
          crypto_key  = "kubecon"
        }

ui:
  enabled: true
  serviceType: LoadBalancer
  loadBalancerSourceRanges: ["96.242.54.120/32"]

csi:
  enabled: false