---
apiVersion: v1
kind: Service
metadata:
  name: expense
  labels:
    app: expense
    release: v1
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
    konghq.com/plugins: tracing
spec:
  selector:
    app: expense
    release: v1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: expense
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense
  labels:
    app: expense
    release: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense
      release: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "expense-db-mssql:1433"
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9411"
        consul.hashicorp.com/service-meta-version: v1
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: "expense"
        vault.hashicorp.com/agent-inject-secret-dbsettings.json: "expense/database/mssql/creds/expense"
        vault.hashicorp.com/agent-inject-template-dbsettings.json: |
          {
            "ConnectionStrings": {
              {{ with secret "expense/database/mssql/creds/expense" -}}
              "ExpensesDatabase": "Server=.;Database=DemoExpenses;user id={{ .Data.username }};password={{ .Data.password }}",
              {{- end }}
            }
          }
      labels:
        app: expense
        release: v1
        framework: dotnet
    spec:
      serviceAccountName: expense
      containers:
        - name: expense
          imagePullPolicy: Always
          image: "joatmon08/expense:dotnet-6.0"
          command: ["/bin/sh"]
          args: ["-c", "cp /vault/secrets/dbsettings.json /app/dbsettings.json && dotnet expense.dll"]
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /api
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
