---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: report-kong-proxy
spec:
  protocol: http
  upstreamConfig:
    overrides:
      - name: report
        passiveHealthCheck:
          interval: "30s"
          maxFailures: 10
      - name: expense
        passiveHealthCheck:
          interval: "10s"
          maxFailures: 3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: report
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/preserve-host: "false"
    konghq.com/plugins: tracing
spec:
  rules:
    - http:
        paths:
          - path: /api/report
            pathType: Prefix
            backend:
              service:
                name: report
                port:
                  number: 5002
          - path: /api/expense
            pathType: Exact
            backend:
              service:
                name: expense
                port:
                  number: 5001
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: tracing
  annotations:
    kubernetes.io/ingress.class: kong
config:
  http_endpoint: http://jaeger.default.svc.cluster.local:9411/api/v2/spans
  sample_ratio: 1
  traceid_byte_count: 16
  header_type: preserve
  default_header_type: b3
  tags_header: Zipkin-Tags
plugin: zipkin
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: prometheus